# Generated by Django 4.2.4 on 2023-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=11, null=True, unique=True, verbose_name='телефон'),
        ),
    ]
